---  
  - name: Test Script
    expect:
      command: bash /ansible-roles/expect-1.sh
      responses:
        enter one: 'one'
        enter two: 'two'
        enter three: 'three'
        enter password: 'pass'
        echo: yes
