---
# tasks file for sambaclient_role
- name: installing samba-client package
  yum:
    name: '{{ pkg1 }}'
    state: present

- name: create a mount directory
  file: 
    path: /mnt/samba
    state: directory

- name: configure /etc/fstab on client
  mount:
    path: /mnt/samba
    src: //192.168.50.218/samba
    fstype: cifs
    opts: credentials=/mnt/samba/.cred
    state: present

