---
 - name: Installing XRDP..
   when: ansible_os_family == "RedHat"
   block: 
     - name: Installing xrdp Package..
       yum: 
         name: "{{ item }}"
         state: present
       with_items: "{{ packages }}"

     - name: Starting and Enabling xrdp..
       service:  
         name: xrdp
         state: started
         enabled: yes
